import type {
  User,
  Recipe,
  WeeklyMealPlan,
  GroceryItem,
} from '@/types';
import { getCurrentWeekOf } from '@/lib/utils';

export const mockUser: User = {
  id: '1',
  fullName: 'John Doe',
  username: 'johndoe',
  email: 'john@example.com',
  dietaryPreferences: ['Vegetarian'],
  allergies: ['Peanuts', 'Shellfish'],
  createdAt: new Date('2025-01-01'),
};

export const mockRecipes: Recipe[] = [
  {
    id: 'r1',
    userId: '1',
    title: 'Avocado Toast',
    description:
      'Simple and nutritious avocado toast perfect for breakfast or lunch',
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: 'Easy',
    costPerServing: 3,
    dietaryTags: ['Vegetarian', 'Vegan'],
    ingredients: [
      { id: 'i1', name: 'Bread', quantity: 2, unit: 'slice' },
      { id: 'i2', name: 'Avocado', quantity: 1, unit: 'piece' },
      { id: 'i3', name: 'Lemon Juice', quantity: 1, unit: 'tbsp' },
      { id: 'i4', name: 'Salt', quantity: 1, unit: 'pinch' },
      { id: 'i5', name: 'Black Pepper', quantity: 1, unit: 'pinch' },
    ],
    steps: [
      {
        id: 's1',
        order: 1,
        description: 'Toast the bread slices until golden and crispy',
      },
      {
        id: 's2',
        order: 2,
        description: 'Mash avocado with lemon juice, salt and pepper',
      },
      {
        id: 's3',
        order: 3,
        description: 'Spread avocado mixture on toast and serve immediately',
      },
    ],
    nutrition: { calories: 320, protein: 8, carbs: 35, fat: 18 },
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date('2025-01-02'),
  },
  {
    id: 'r2',
    userId: '1',
    title: 'Grilled Chicken Salad',
    description:
      'Fresh and protein-packed salad with grilled chicken and crispy vegetables',
    prepTime: 20,
    cookTime: 15,
    servings: 2,
    difficulty: 'Easy',
    costPerServing: 8,
    dietaryTags: ['Gluten-Free'],
    ingredients: [
      { id: 'i6', name: 'Chicken Breast', quantity: 200, unit: 'g' },
      { id: 'i7', name: 'Mixed Greens', quantity: 100, unit: 'g' },
      { id: 'i8', name: 'Cherry Tomatoes', quantity: 10, unit: 'piece' },
      { id: 'i9', name: 'Cucumber', quantity: 1, unit: 'piece' },
      { id: 'i10', name: 'Olive Oil', quantity: 2, unit: 'tbsp' },
      { id: 'i11', name: 'Lemon', quantity: 1, unit: 'piece' },
    ],
    steps: [
      {
        id: 's4',
        order: 1,
        description: 'Season chicken breast with salt, pepper and olive oil',
      },
      {
        id: 's5',
        order: 2,
        description: 'Grill chicken for 6-7 minutes each side until cooked through',
      },
      {
        id: 's6',
        order: 3,
        description: 'Let chicken rest 5 minutes then slice',
      },
      {
        id: 's7',
        order: 4,
        description: 'Combine greens, tomatoes and cucumber in bowl',
      },
      {
        id: 's8',
        order: 5,
        description: 'Top with sliced chicken and drizzle with lemon juice',
      },
    ],
    nutrition: { calories: 380, protein: 42, carbs: 12, fat: 18 },
    createdAt: new Date('2025-01-03'),
    updatedAt: new Date('2025-01-03'),
  },
  {
    id: 'r3',
    userId: '1',
    title: 'Pasta Primavera',
    description: 'Light and colorful pasta loaded with fresh spring vegetables',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'Medium',
    costPerServing: 6,
    dietaryTags: ['Vegetarian'],
    ingredients: [
      { id: 'i12', name: 'Pasta', quantity: 400, unit: 'g' },
      { id: 'i13', name: 'Zucchini', quantity: 1, unit: 'piece' },
      { id: 'i14', name: 'Cherry Tomatoes', quantity: 200, unit: 'g' },
      { id: 'i15', name: 'Bell Pepper', quantity: 1, unit: 'piece' },
      { id: 'i16', name: 'Garlic', quantity: 3, unit: 'clove' },
      { id: 'i17', name: 'Olive Oil', quantity: 3, unit: 'tbsp' },
      { id: 'i18', name: 'Parmesan', quantity: 50, unit: 'g' },
    ],
    steps: [
      {
        id: 's9',
        order: 1,
        description: 'Cook pasta according to package directions, reserve 1 cup pasta water',
      },
      {
        id: 's10',
        order: 2,
        description: 'Saute minced garlic in olive oil for 1 minute',
      },
      {
        id: 's11',
        order: 3,
        description: 'Add vegetables and cook for 5-6 minutes until tender',
      },
      {
        id: 's12',
        order: 4,
        description: 'Toss with drained pasta and pasta water as needed',
      },
      {
        id: 's13',
        order: 5,
        description: 'Top with grated parmesan and serve immediately',
      },
    ],
    nutrition: { calories: 450, protein: 14, carbs: 72, fat: 12 },
    createdAt: new Date('2025-01-04'),
    updatedAt: new Date('2025-01-04'),
  },
  {
    id: 'r4',
    userId: '1',
    title: 'Beef Stir Fry',
    description:
      'Quick and flavorful beef stir fry with colorful vegetables over steamed rice',
    prepTime: 20,
    cookTime: 15,
    servings: 3,
    difficulty: 'Medium',
    costPerServing: 10,
    dietaryTags: [],
    ingredients: [
      { id: 'i19', name: 'Beef Strips', quantity: 300, unit: 'g' },
      { id: 'i20', name: 'Broccoli', quantity: 200, unit: 'g' },
      { id: 'i21', name: 'Bell Peppers', quantity: 2, unit: 'piece' },
      { id: 'i22', name: 'Soy Sauce', quantity: 3, unit: 'tbsp' },
      { id: 'i23', name: 'Ginger', quantity: 1, unit: 'tsp' },
      { id: 'i24', name: 'Garlic', quantity: 2, unit: 'clove' },
      { id: 'i25', name: 'Sesame Oil', quantity: 1, unit: 'tbsp' },
      { id: 'i26', name: 'Rice', quantity: 2, unit: 'cup' },
    ],
    steps: [
      {
        id: 's14',
        order: 1,
        description: 'Cook rice according to package directions',
      },
      {
        id: 's15',
        order: 2,
        description: 'Marinate beef strips in soy sauce and ginger for 10 minutes',
      },
      {
        id: 's16',
        order: 3,
        description: 'Stir fry vegetables in sesame oil on high heat for 3-4 minutes',
      },
      {
        id: 's17',
        order: 4,
        description: 'Add beef and cook for 3-4 minutes until browned',
      },
      {
        id: 's18',
        order: 5,
        description: 'Combine everything and serve over rice',
      },
    ],
    nutrition: { calories: 520, protein: 38, carbs: 45, fat: 18 },
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-05'),
  },
  {
    id: 'r5',
    userId: '1',
    title: 'Smoothie Bowl',
    description:
      'Vibrant and nutritious smoothie bowl topped with fresh fruits and granola',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: 'Easy',
    costPerServing: 4,
    dietaryTags: ['Vegan', 'Gluten-Free'],
    ingredients: [
      { id: 'i27', name: 'Frozen Berries', quantity: 200, unit: 'g' },
      { id: 'i28', name: 'Banana', quantity: 1, unit: 'piece' },
      { id: 'i29', name: 'Almond Milk', quantity: 100, unit: 'ml' },
      { id: 'i30', name: 'Granola', quantity: 50, unit: 'g' },
      { id: 'i31', name: 'Honey', quantity: 1, unit: 'tbsp' },
      { id: 'i32', name: 'Chia Seeds', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      {
        id: 's19',
        order: 1,
        description: 'Blend frozen berries, banana and almond milk until thick and smooth',
      },
      {
        id: 's20',
        order: 2,
        description: 'Pour into bowl and top with granola, honey and chia seeds',
      },
    ],
    nutrition: { calories: 380, protein: 8, carbs: 72, fat: 8 },
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date('2025-01-06'),
  },
  {
    id: 'r6',
    userId: '1',
    title: 'Oatmeal with Berries',
    description:
      'Warm and comforting oatmeal topped with fresh berries and natural sweeteners',
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    difficulty: 'Easy',
    costPerServing: 2,
    dietaryTags: ['Vegan', 'Gluten-Free'],
    ingredients: [
      { id: 'i33', name: 'Oats', quantity: 80, unit: 'g' },
      { id: 'i34', name: 'Almond Milk', quantity: 300, unit: 'ml' },
      { id: 'i35', name: 'Mixed Berries', quantity: 100, unit: 'g' },
      { id: 'i36', name: 'Honey', quantity: 1, unit: 'tbsp' },
      { id: 'i37', name: 'Cinnamon', quantity: 1, unit: 'tsp' },
      { id: 'i38', name: 'Chia Seeds', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      {
        id: 's21',
        order: 1,
        description: 'Heat almond milk in saucepan over medium heat',
      },
      {
        id: 's22',
        order: 2,
        description: 'Add oats and cook for 5 minutes stirring occasionally',
      },
      {
        id: 's23',
        order: 3,
        description: 'Top with berries, honey and cinnamon and serve hot',
      },
    ],
    nutrition: { calories: 350, protein: 10, carbs: 62, fat: 6 },
    createdAt: new Date('2025-01-07'),
    updatedAt: new Date('2025-01-07'),
  },
];

export const mockMealPlan: WeeklyMealPlan = {
  weekOf: getCurrentWeekOf(),
  entries: [
    {
      id: 'mp1',
      recipeId: 'r6',
      recipe: mockRecipes[5],
      day: 'Monday',
      mealType: 'Breakfast',
      weekOf: getCurrentWeekOf(),
    },
    {
      id: 'mp2',
      recipeId: 'r1',
      recipe: mockRecipes[0],
      day: 'Monday',
      mealType: 'Lunch',
      weekOf: getCurrentWeekOf(),
    },
    {
      id: 'mp3',
      recipeId: 'r3',
      recipe: mockRecipes[2],
      day: 'Tuesday',
      mealType: 'Dinner',
      weekOf: getCurrentWeekOf(),
    },
    {
      id: 'mp4',
      recipeId: 'r2',
      recipe: mockRecipes[1],
      day: 'Wednesday',
      mealType: 'Lunch',
      weekOf: getCurrentWeekOf(),
    },
    {
      id: 'mp5',
      recipeId: 'r5',
      recipe: mockRecipes[4],
      day: 'Thursday',
      mealType: 'Breakfast',
      weekOf: getCurrentWeekOf(),
    },
    {
      id: 'mp6',
      recipeId: 'r4',
      recipe: mockRecipes[3],
      day: 'Friday',
      mealType: 'Dinner',
      weekOf: getCurrentWeekOf(),
    },
    {
      id: 'mp7',
      recipeId: 'r1',
      recipe: mockRecipes[0],
      day: 'Saturday',
      mealType: 'Lunch',
      weekOf: getCurrentWeekOf(),
    },
  ],
};

export const mockGroceryList: GroceryItem[] = [
  {
    id: 'g1',
    name: 'Oats',
    quantity: 80,
    unit: 'g',
    category: 'Grains & Pasta',
    estimatedCost: 1.5,
    isPurchased: true,
    isInPantry: false,
    fromRecipes: ['Oatmeal with Berries'],
  },
  {
    id: 'g2',
    name: 'Almond Milk',
    quantity: 400,
    unit: 'ml',
    category: 'Dairy',
    estimatedCost: 2.0,
    isPurchased: true,
    isInPantry: false,
    fromRecipes: ['Oatmeal with Berries', 'Smoothie Bowl'],
  },
  {
    id: 'g3',
    name: 'Mixed Berries',
    quantity: 300,
    unit: 'g',
    category: 'Produce',
    estimatedCost: 4.0,
    isPurchased: false,
    isInPantry: false,
    fromRecipes: ['Oatmeal with Berries', 'Smoothie Bowl'],
  },
  {
    id: 'g4',
    name: 'Avocado',
    quantity: 2,
    unit: 'piece',
    category: 'Produce',
    estimatedCost: 3.0,
    isPurchased: false,
    isInPantry: false,
    fromRecipes: ['Avocado Toast', 'Avocado Toast'],
  },
  {
    id: 'g5',
    name: 'Bread',
    quantity: 4,
    unit: 'slice',
    category: 'Grains & Pasta',
    estimatedCost: 1.0,
    isPurchased: true,
    isInPantry: false,
    fromRecipes: ['Avocado Toast', 'Avocado Toast'],
  },
  {
    id: 'g6',
    name: 'Cherry Tomatoes',
    quantity: 210,
    unit: 'g',
    category: 'Produce',
    estimatedCost: 2.5,
    isPurchased: false,
    isInPantry: false,
    fromRecipes: ['Grilled Chicken Salad', 'Pasta Primavera'],
  },
  {
    id: 'g7',
    name: 'Chicken Breast',
    quantity: 200,
    unit: 'g',
    category: 'Meat & Protein',
    estimatedCost: 5.0,
    isPurchased: false,
    isInPantry: false,
    fromRecipes: ['Grilled Chicken Salad'],
  },
  {
    id: 'g8',
    name: 'Pasta',
    quantity: 400,
    unit: 'g',
    category: 'Grains & Pasta',
    estimatedCost: 2.0,
    isPurchased: false,
    isInPantry: true,
    fromRecipes: ['Pasta Primavera'],
  },
  {
    id: 'g9',
    name: 'Olive Oil',
    quantity: 5,
    unit: 'tbsp',
    category: 'Spices & Condiments',
    estimatedCost: 1.5,
    isPurchased: false,
    isInPantry: true,
    fromRecipes: ['Grilled Chicken Salad', 'Pasta Primavera'],
  },
  {
    id: 'g10',
    name: 'Beef Strips',
    quantity: 300,
    unit: 'g',
    category: 'Meat & Protein',
    estimatedCost: 8.0,
    isPurchased: false,
    isInPantry: false,
    fromRecipes: ['Beef Stir Fry'],
  },
  {
    id: 'g11',
    name: 'Broccoli',
    quantity: 200,
    unit: 'g',
    category: 'Produce',
    estimatedCost: 1.5,
    isPurchased: false,
    isInPantry: false,
    fromRecipes: ['Beef Stir Fry'],
  },
  {
    id: 'g12',
    name: 'Frozen Berries',
    quantity: 200,
    unit: 'g',
    category: 'Produce',
    estimatedCost: 3.0,
    isPurchased: false,
    isInPantry: false,
    fromRecipes: ['Smoothie Bowl'],
  },
];
